# Implementación del método de eliminación de Gauss-Jordan

**Nombre:** Heriberto Espino Montelongo

**Materia:** Análisis numérico

**Sección:** 1

**Fecha:** 23/09/2024

In [229]:
import numpy as np

## Declaración

Matriz de coeficientes y vector de términos independientes

In [230]:
A = np.array([[1, 1, 1], [2, 3, -1], [6, -2, -3]])
B = np.array([[6], [5], [-7]])

In [231]:
# # Exercise 1: One solution
# A = np.array([[3, -2], [5, 2]])
# B = np.array([[4], [12]])

In [232]:
# # Exercise 2: Infinitely many solutions
# A = np.array([[1 ,-1], [2, -2]])
# B = np.array([[7], [14]])

In [233]:
# # Exercise 3: No solution
# A = np.array([[1 ,-1], [2, -2]])
# B = np.array([[7], [10]])

Tamaño y dimensión de un "array"

In [234]:
print("Matrix A:\n", A, "\n")

sizeA = np.shape(A)

print("Type of matrix A:\t\t", type(A))
print("Size of matrix A:\t\t", sizeA)
print("Dimension of matrix A:\t\t", np.ndim(A))
print("Number of rows in matrix A:\t", sizeA[0])
print("Number of columns in matrix A:\t", sizeA[1])

Matrix A:
 [[ 1  1  1]
 [ 2  3 -1]
 [ 6 -2 -3]] 

Type of matrix A:		 <class 'numpy.ndarray'>
Size of matrix A:		 (3, 3)
Dimension of matrix A:		 2
Number of rows in matrix A:	 3
Number of columns in matrix A:	 3


In [235]:
print("Matrix B:\n", B, "\n")

sizeB = np.shape(B)

print("Type of matrix B:\t\t", type(B))
print("Size of matrix B:\t\t", sizeB)
print("Dimension of matrix B:\t\t", np.ndim(B))
print("Number of rows in matrix B:\t", sizeB[0])
print("Number of columns in matrix B:\t", sizeB[1])

Matrix B:
 [[ 6]
 [ 5]
 [-7]] 

Type of matrix B:		 <class 'numpy.ndarray'>
Size of matrix B:		 (3, 1)
Dimension of matrix B:		 2
Number of rows in matrix B:	 3
Number of columns in matrix B:	 1


## Matriz aumentada

In [236]:
C = np.concatenate((A, B), axis=1)
print("Matrix C:\n", C, "\n")

sizeC = np.shape(C)

print("Type of matrix C:\t\t", type(C))
print("Size of matrix C:\t\t", sizeC)
print("Dimension of matrix C:\t\t", np.ndim(C))
print("Number of rows in matrix C:\t", sizeC[0])
print("Number of columns in matrix C:\t", sizeC[1])

Matrix C:
 [[ 1  1  1  6]
 [ 2  3 -1  5]
 [ 6 -2 -3 -7]] 

Type of matrix C:		 <class 'numpy.ndarray'>
Size of matrix C:		 (3, 4)
Dimension of matrix C:		 2
Number of rows in matrix C:	 3
Number of columns in matrix C:	 4


## Solve

In [237]:
X = np.linalg.solve(A, B)
print("Solution X:\n", X)

Solution X:
 [[1.]
 [2.]
 [3.]]


# Implementación del método


In [238]:
for row in range(sizeC[0]):
    print("Row:", row)
    for col in range(sizeC[1]):
        print("Column:", col, "C[", row, "][", col, "]:", C[row][col])

Row: 0
Column: 0 C[ 0 ][ 0 ]: 1
Column: 1 C[ 0 ][ 1 ]: 1
Column: 2 C[ 0 ][ 2 ]: 1
Column: 3 C[ 0 ][ 3 ]: 6
Row: 1
Column: 0 C[ 1 ][ 0 ]: 2
Column: 1 C[ 1 ][ 1 ]: 3
Column: 2 C[ 1 ][ 2 ]: -1
Column: 3 C[ 1 ][ 3 ]: 5
Row: 2
Column: 0 C[ 2 ][ 0 ]: 6
Column: 1 C[ 2 ][ 1 ]: -2
Column: 2 C[ 2 ][ 2 ]: -3
Column: 3 C[ 2 ][ 3 ]: -7


In [240]:
for c in range(sizeC[1] - 1):  # -1 to avoid the last column, because C is an augmented matrix
    print("-----------------------------------")
    print("Column:", c)
    if C[c][c] != 1 and C[c][c] != 0:
        C[c, :] = C[c, :] / C[c][c]
        print("C[c,:]:", C[c, :])
    else:
        print("We have our pivot at C[", c, "][", c, "]")
        print("C[c,:]:", C[c, :])

    for r in range(sizeC[0]):
        print("Row:", r)
        if r != c:
            C[r, :] = C[r, :] - C[r][c] * C[c, :]
            print("C[r,:]:", C[r, :])
            print("Modified C:\n", C, "\n")
        else:
            print("The index of the row is the same as the index of the column")

print("Modified C:\n", C, "\n")

-----------------------------------
Column: 0
We have our pivot at C[ 0 ][ 0 ]
C[c,:]: [1 1 1 6]
Row: 0
The index of the row is the same as the index of the column
Row: 1
C[r,:]: [ 0  1 -3 -7]
Modified C:
 [[ 1  1  1  6]
 [ 0  1 -3 -7]
 [ 6 -2 -3 -7]] 

Row: 2
C[r,:]: [  0  -8  -9 -43]
Modified C:
 [[  1   1   1   6]
 [  0   1  -3  -7]
 [  0  -8  -9 -43]] 

-----------------------------------
Column: 1
We have our pivot at C[ 1 ][ 1 ]
C[c,:]: [ 0  1 -3 -7]
Row: 0
C[r,:]: [ 1  0  4 13]
Modified C:
 [[  1   0   4  13]
 [  0   1  -3  -7]
 [  0  -8  -9 -43]] 

Row: 1
The index of the row is the same as the index of the column
Row: 2
C[r,:]: [  0   0 -33 -99]
Modified C:
 [[  1   0   4  13]
 [  0   1  -3  -7]
 [  0   0 -33 -99]] 

-----------------------------------
Column: 2
C[c,:]: [0 0 1 3]
Row: 0
C[r,:]: [1 0 0 1]
Modified C:
 [[ 1  0  0  1]
 [ 0  1 -3 -7]
 [ 0  0  1  3]] 

Row: 1
C[r,:]: [0 1 0 2]
Modified C:
 [[1 0 0 1]
 [0 1 0 2]
 [0 0 1 3]] 

Row: 2
The index of the row is the same 