# Gauss-Jordan

**Nombre:** Heriberto Espino Montelongo

**Materia:** Análisis numérico

**Sección:** 1

**Fecha:** 25/09/2024

En este documento, abordaremos la verificación y resolución de sistemas de ecuaciones lineales utilizando el método de Gauss-Jordan.

#### Verificación de Sistemas de Ecuaciones Lineales

1. Verificar que es un Sistema de ecuaciones lineales.
     - Si tiene una potencia $x^2$ no es
     - Si tiene un producto $2xy$ no es 

2. ¿Tiene soluciones?
     - Si tiene un renglón de ceros, se pone $x_1 - x_2 = 7$
     - Si tiene un renglon con $0 = -4$ no tiene soluciones
     - Si tiene la diagonal de unos, tiene una única solución.

In [70]:
import numpy as np

def gaussian_elimination(A, B):

    print("Ecuación matricial Ax = b del sistema")
    # Determine the width of the columns
    col_width = max(len("{:.2f}".format(num)) for row in A for num in row) + 2
    vec_width = max(len("{:.2f}".format(num)) for num in B.flatten()) + 2

    # Print matrix A and vector B in columns
    for i in range(A.shape[0]):
        row = ["{:.2f}".format(num).rjust(col_width) for num in A[i]]
        if i == A.shape[0] // 2:
            print("[{}]  *  [x{}]  =  [{}]".format(" ".join(row), i + 1, "{:.2f}".format(B[i, 0]).rjust(vec_width)))
        else:
            print("[{}]     [x{}]     [{}]".format(" ".join(row), i + 1, "{:.2f}".format(B[i, 0]).rjust(vec_width)))

    # Concatenate A and B to form the augmented matrix
    C = np.concatenate((A, B), axis=1)
    print("\nMatriz aumentada asociada al sistema:\n", C, "\n")

    # Convert C to float
    C = np.array(C, dtype=float)

    sizeA = np.shape(A)
    sizeB = np.shape(B)
    sizeC = np.shape(C)

    print("Tamaño de A:\n", sizeA)
    print("\nTamaño de B:\n", sizeB)

    # Gaussian elimination
    for c in range(sizeC[1] - 1):  # -1 to avoid the last column, because C is an augmented matrix
        if C[c][c] != 1 and C[c][c] != 0:
            C[c, :] = C[c, :] / C[c][c]

        for r in range(sizeC[0]):
            if r != c:
                C[r, :] = C[r, :] - C[r][c] * C[c, :]

    print("\nMatriz escalonada reducida:\n", C)

    # Check for no solution or infinite solutions
    pivots = []  # Lista para almacenar las columnas de los pivotes

    for r in range(sizeC[0]):
        
        # Caso: el sistema no tiene solución
        if np.all(C[r, :-1] == 0) and C[r, -1] != 0:
            print("\nEl sistema no tiene solución.")
            return

        # Caso: el sistema tiene infinitas soluciones
        elif np.all(C[r, :-1] == 0) and C[r, -1] == 0:
            print("\nEl sistema tiene infinitas soluciones.")
            
            # Imprimir las ecuaciones de las filas no nulas
            for r in range(sizeC[0]):
                if not np.all(C[r, :-1] == 0):
                    equation = " + ".join([f"{C[r, c]:.3f}*x{c+1}" for c in range(sizeC[1] - 1) if C[r, c] != 0])
                    print(f"{equation} = {C[r, -1]:.3f}")
                    # Registrar el índice de las variables pivote
                    for c in range(sizeC[1] - 1):
                        if C[r, c] != 0:
                            pivots.append(c)
                            break
            
            # Identificar e imprimir las variables libres
            free_vars = [f"x{c+1}" for c in range(sizeC[1] - 1) if c not in pivots]
            
            if free_vars:
                for var in free_vars:
                    print(f"{var} ∈ ℝ")
            else:
                print("\nNo hay variables libres.")
            
            return



    # Back substitution to find the solution
    x = np.zeros(sizeA[1])
    for i in range(sizeA[0] - 1, -1, -1):
        x[i] = (C[i, -1] - np.dot(C[i, :-1], x)) / C[i, i]

    print("\nSolución del sistema:")
    for i in range(len(x)):
        print("x{} = {}".format(i + 1, x[i]))

### Ejercicio 1

$$
3x_1 - 2x_2 = 4 \\
5x_1 + 2x_2 = 12
$$

In [71]:
# Exercise 1: One solution
A = np.array([[3, -2], [5, 2]])
B = np.array([[4], [12]])

gaussian_elimination(A, B)

Ecuación matricial Ax = b del sistema
[   3.00   -2.00]     [x1]     [   4.00]
[   5.00    2.00]  *  [x2]  =  [  12.00]

Matriz aumentada asociada al sistema:
 [[ 3 -2  4]
 [ 5  2 12]] 

Tamaño de A:
 (2, 2)

Tamaño de B:
 (2, 1)

Matriz escalonada reducida:
 [[1. 0. 2.]
 [0. 1. 1.]]

Solución del sistema:
x1 = 2.0
x2 = 1.0000000000000002


### Ejercicio 2

$$
x_1 - x_2 = 7 \\
2x_1 - 2x_2 = 14
$$

In [72]:
# Exercise 2: Infinitely many solutions
A = np.array([[1, -1], [2, -2]])
B = np.array([[7], [14]])

gaussian_elimination(A, B)

Ecuación matricial Ax = b del sistema
[   1.00   -1.00]     [x1]     [   7.00]
[   2.00   -2.00]  *  [x2]  =  [  14.00]

Matriz aumentada asociada al sistema:
 [[ 1 -1  7]
 [ 2 -2 14]] 

Tamaño de A:
 (2, 2)

Tamaño de B:
 (2, 1)

Matriz escalonada reducida:
 [[ 1. -1.  7.]
 [ 0.  0.  0.]]

El sistema tiene infinitas soluciones.
1.000*x1 + -1.000*x2 = 7.000
x2 ∈ ℝ


### Ejercicio 3

$$
x_1 - x_2 = 7 \\
2x_1 - 2x_2 = 10
$$

In [73]:
# # Exercise 3: No solution
A = np.array([[1, -1], [2, -2]])
B = np.array([[7], [10]])

gaussian_elimination(A, B)

Ecuación matricial Ax = b del sistema
[   1.00   -1.00]     [x1]     [   7.00]
[   2.00   -2.00]  *  [x2]  =  [  10.00]

Matriz aumentada asociada al sistema:
 [[ 1 -1  7]
 [ 2 -2 10]] 

Tamaño de A:
 (2, 2)

Tamaño de B:
 (2, 1)

Matriz escalonada reducida:
 [[ 1. -1.  3.]
 [ 0.  0. -4.]]

El sistema no tiene solución.


### Ejercicio 4

$$
2x - 3y + z = -1 \\
x - y + 2z = -3 \\
3x + y - z = 9
$$

In [74]:
# Exercise 4:
A = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
B = np.array([[-1], [-3], [9]])

gaussian_elimination(A, B)

Ecuación matricial Ax = b del sistema
[   2.00   -3.00    1.00]     [x1]     [  -1.00]
[   1.00   -1.00    2.00]  *  [x2]  =  [  -3.00]
[   3.00    1.00   -1.00]     [x3]     [   9.00]

Matriz aumentada asociada al sistema:
 [[ 2 -3  1 -1]
 [ 1 -1  2 -3]
 [ 3  1 -1  9]] 

Tamaño de A:
 (3, 3)

Tamaño de B:
 (3, 1)

Matriz escalonada reducida:
 [[ 1.  0.  0.  2.]
 [ 0.  1.  0.  1.]
 [-0. -0.  1. -2.]]

Solución del sistema:
x1 = 2.0
x2 = 1.0
x3 = -2.0


### Ejercicio 5

$$
x - y + 4z = -5 \\
3x + z = 0 \\
-x + y - 4z = 20
$$


In [75]:
# Exercise 5:
A = np.array([[1, -1, 4], [3, 0, 1], [-1, 1, -4]])
B = np.array([[-5], [0], [20]])

gaussian_elimination(A, B)

Ecuación matricial Ax = b del sistema
[   1.00   -1.00    4.00]     [x1]     [  -5.00]
[   3.00    0.00    1.00]  *  [x2]  =  [   0.00]
[  -1.00    1.00   -4.00]     [x3]     [  20.00]

Matriz aumentada asociada al sistema:
 [[ 1 -1  4 -5]
 [ 3  0  1  0]
 [-1  1 -4 20]] 

Tamaño de A:
 (3, 3)

Tamaño de B:
 (3, 1)

Matriz escalonada reducida:
 [[ 1.          0.          0.33333333 -5.        ]
 [ 0.          1.         -3.66666667 60.        ]
 [ 0.          0.          0.         15.        ]]

El sistema no tiene solución.


### Ejercicio 6

$$
-x + y + 2z = 0 \\
x + 2y + z = 6 \\
-2x - y + z = -6
$$


In [76]:
# Exercise 6:
A = np.array([[-1, 1, 2], [1, 2, 1], [-2, -1, 1]])
B = np.array([[0], [6], [-6]])

gaussian_elimination(A, B)

Ecuación matricial Ax = b del sistema
[  -1.00    1.00    2.00]     [x1]     [   0.00]
[   1.00    2.00    1.00]  *  [x2]  =  [   6.00]
[  -2.00   -1.00    1.00]     [x3]     [  -6.00]

Matriz aumentada asociada al sistema:
 [[-1  1  2  0]
 [ 1  2  1  6]
 [-2 -1  1 -6]] 

Tamaño de A:
 (3, 3)

Tamaño de B:
 (3, 1)

Matriz escalonada reducida:
 [[ 1.  0. -1.  2.]
 [ 0.  1.  1.  2.]
 [ 0.  0.  0.  0.]]

El sistema tiene infinitas soluciones.
1.000*x1 + -1.000*x3 = 2.000
1.000*x2 + 1.000*x3 = 2.000
x3 ∈ ℝ


### Ejercicio 7

$$
0.4p_1 + 0.2p_2 + 0.2p_3 = p_1 \\
0.1p_1 + 0.7p_2 + 0.2p_3 = p_2 \\
0.5p_1 + 0.1p_2 + 0.6p_3 = p_3
$$


In [77]:
# Exercise 7:
A = np.array([[0.4, 0.2, 0.2], [0.1, 0.7, 0.2], [0.5, 0.1, 0.6]])
B = np.array([[0], [0], [0]])

gaussian_elimination(A, B)

Ecuación matricial Ax = b del sistema
[  0.40   0.20   0.20]     [x1]     [  0.00]
[  0.10   0.70   0.20]  *  [x2]  =  [  0.00]
[  0.50   0.10   0.60]     [x3]     [  0.00]

Matriz aumentada asociada al sistema:
 [[0.4 0.2 0.2 0. ]
 [0.1 0.7 0.2 0. ]
 [0.5 0.1 0.6 0. ]] 

Tamaño de A:
 (3, 3)

Tamaño de B:
 (3, 1)

Matriz escalonada reducida:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]

Solución del sistema:
x1 = 0.0
x2 = 0.0
x3 = 0.0


### Ejercicio 8

$$
0.2p_1 + 0.7p_2 = p_1 \\
0.8p_1 + 0.3p_2 = p_2
$$

In [78]:
# Exercise 8:
A = np.array([[-0.8, 0.7], [0.8, -0.7]])
B = np.array([[0], [0]])

gaussian_elimination(A, B)

Ecuación matricial Ax = b del sistema
[  -0.80    0.70]     [x1]     [  0.00]
[   0.80   -0.70]  *  [x2]  =  [  0.00]

Matriz aumentada asociada al sistema:
 [[-0.8  0.7  0. ]
 [ 0.8 -0.7  0. ]] 

Tamaño de A:
 (2, 2)

Tamaño de B:
 (2, 1)

Matriz escalonada reducida:
 [[ 1.    -0.875  0.   ]
 [ 0.     0.     0.   ]]

El sistema tiene infinitas soluciones.
1.000*x1 + -0.875*x2 = 0.000
x2 ∈ ℝ


### Ejercicio 9

$$
-0.8p_1 + 0.8p_2 + 0.4p_3 = 0 \\
0.3p_1 - 0.9p_2 + 0.4p_3 = 0 \\
0.5p_1 + 0.1p_2 - 0.8p_3 = 0
$$

In [79]:
# Exercise 9:
A = np.array([[-0.8, 0.8, 0.4], [0.3, -0.9, 0.4], [0.5, 0.1, -0.8]])
B = np.array([[0], [0], [0]])

gaussian_elimination(A, B)

Ecuación matricial Ax = b del sistema
[  -0.80    0.80    0.40]     [x1]     [  0.00]
[   0.30   -0.90    0.40]  *  [x2]  =  [  0.00]
[   0.50    0.10   -0.80]     [x3]     [  0.00]

Matriz aumentada asociada al sistema:
 [[-0.8  0.8  0.4  0. ]
 [ 0.3 -0.9  0.4  0. ]
 [ 0.5  0.1 -0.8  0. ]] 

Tamaño de A:
 (3, 3)

Tamaño de B:
 (3, 1)

Matriz escalonada reducida:
 [[ 1.  0.  0. -0.]
 [-0.  1.  0. -0.]
 [-0. -0.  1. -0.]]

Solución del sistema:
x1 = -0.0
x2 = -0.0
x3 = -0.0


### Ejercicio 10

$$
.65p_1 + 0.3p_2 + 0.3p_3 + 0.2p_4 = p_1 \\
0.1p_1 + 0.1p_2 + 0.15p_3 + 0.1p_4 = p_2 \\
0.25p_1 + 0.35p_2 + 0.15p_3 + 0.3p_4 = p_3 \\
0.25p_2 + 0.4p_3 + 0.4p_4 = p_4
$$

In [80]:
# Exercise 10:
A = np.array([[-0.35, 0.3, 0.3, 0.2], [0.1, -0.9, 0.15, 0.1], [0.25, 0.35, -0.85, 0.3], [0, 0.25, 0.4, -0.6]])
B = np.array([[0], [0], [0], [0]])

gaussian_elimination(A, B)

Ecuación matricial Ax = b del sistema
[  -0.35    0.30    0.30    0.20]     [x1]     [  0.00]
[   0.10   -0.90    0.15    0.10]     [x2]     [  0.00]
[   0.25    0.35   -0.85    0.30]  *  [x3]  =  [  0.00]
[   0.00    0.25    0.40   -0.60]     [x4]     [  0.00]

Matriz aumentada asociada al sistema:
 [[-0.35  0.3   0.3   0.2   0.  ]
 [ 0.1  -0.9   0.15  0.1   0.  ]
 [ 0.25  0.35 -0.85  0.3   0.  ]
 [ 0.    0.25  0.4  -0.6   0.  ]] 

Tamaño de A:
 (4, 4)

Tamaño de B:
 (4, 1)

Matriz escalonada reducida:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]

Solución del sistema:
x1 = 0.0
x2 = 0.0
x3 = 0.0
x4 = 0.0


In [81]:
# Exercise 10:
A = np.array([[-35, 3, 3, 2], [1, -9, 15, 1], [25, 35, -85, 3], [0, 25, 4, -6]])
B = np.array([[0], [0], [0], [0]])

gaussian_elimination(A, B)

Ecuación matricial Ax = b del sistema
[  -35.00     3.00     3.00     2.00]     [x1]     [  0.00]
[    1.00    -9.00    15.00     1.00]     [x2]     [  0.00]
[   25.00    35.00   -85.00     3.00]  *  [x3]  =  [  0.00]
[    0.00    25.00     4.00    -6.00]     [x4]     [  0.00]

Matriz aumentada asociada al sistema:
 [[-35   3   3   2   0]
 [  1  -9  15   1   0]
 [ 25  35 -85   3   0]
 [  0  25   4  -6   0]] 

Tamaño de A:
 (4, 4)

Tamaño de B:
 (4, 1)

Matriz escalonada reducida:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]

Solución del sistema:
x1 = 0.0
x2 = 0.0
x3 = 0.0
x4 = 0.0



### Ejercicio 11

$$
2xy + y - z = 3 \\
x + y + z = 1 \\
x - 2y - 3z^2 = 4
$$

Ejercicio 11 (No lineal)
No se incluye, ya que no es un sistema de ecuaciones lineales.
Hay un $xy$

### Ejercicio 12

$$
\sqrt{x} + yz = 6 \\
2x + 3y - z = 5 \\
6x - 2y - 3z = -7
$$

Ejercicio 12 (No lineal)
No se incluye, ya que no es un sistema de ecuaciones lineales.
Hay un $\sqrt{x}$

### Ejercicio 13

$$
x + y^2 z = 6 \\
2x + 3y - z = 5 \\
6xy - 2y - 3z = -7
$$

Ejercicio 13 (No lineal)
No se incluye, ya que no es un sistema de ecuaciones lineales.
Hay un $y^2z$

### Ejercicio 14
$$
x + 4y + 3z^2 = 2 \\
2xy - 6y + 6z = -3 \\
5x - 2y + 3z = -5
$$

Ejercicio 14 (No lineal)
No se incluye, ya que no es un sistema de ecuaciones lineales.
Hay un $3z^2$

### Ejercicio 15
$$
x + y + z = 6 \\
2y + 3y - z = 5 \\
6x - 2y - 3z = -7
$$

In [82]:
# Exercise 15:
A = np.array([[1, 1, 1], [0, 5, -1], [6, -2, -3]])
B = np.array([[6], [5], [-7]])

gaussian_elimination(A, B)

Ecuación matricial Ax = b del sistema
[   1.00    1.00    1.00]     [x1]     [   6.00]
[   0.00    5.00   -1.00]  *  [x2]  =  [   5.00]
[   6.00   -2.00   -3.00]     [x3]     [  -7.00]

Matriz aumentada asociada al sistema:
 [[ 1  1  1  6]
 [ 0  5 -1  5]
 [ 6 -2 -3 -7]] 

Tamaño de A:
 (3, 3)

Tamaño de B:
 (3, 1)

Matriz escalonada reducida:
 [[ 1.          0.          0.          1.03773585]
 [ 0.          1.          0.          1.66037736]
 [-0.         -0.          1.          3.30188679]]

Solución del sistema:
x1 = 1.0377358490566042
x2 = 1.6603773584905661
x3 = 3.30188679245283


## ¡¡Cuidado con los decimales!!

In [83]:
A = np.array([[-6, 2, 2],[1, -3, 2], [5, 1, -4]])
B = np.array([[0], [0], [0]])

gaussian_elimination(A, B)

Ecuación matricial Ax = b del sistema
[  -6.00    2.00    2.00]     [x1]     [  0.00]
[   1.00   -3.00    2.00]  *  [x2]  =  [  0.00]
[   5.00    1.00   -4.00]     [x3]     [  0.00]

Matriz aumentada asociada al sistema:
 [[-6  2  2  0]
 [ 1 -3  2  0]
 [ 5  1 -4  0]] 

Tamaño de A:
 (3, 3)

Tamaño de B:
 (3, 1)

Matriz escalonada reducida:
 [[ 1.     0.    -0.625  0.   ]
 [ 0.     1.    -0.875  0.   ]
 [ 0.     0.     0.     0.   ]]

El sistema tiene infinitas soluciones.
1.000*x1 + -0.625*x3 = 0.000
1.000*x2 + -0.875*x3 = 0.000
x3 ∈ ℝ


In [84]:
A = np.array([[-.6, .2, .2],[.1, -.3, .2], [.5, .1, -.4]])
B = np.array([[0], [0], [0]])

gaussian_elimination(A, B)

Ecuación matricial Ax = b del sistema
[  -0.60    0.20    0.20]     [x1]     [  0.00]
[   0.10   -0.30    0.20]  *  [x2]  =  [  0.00]
[   0.50    0.10   -0.40]     [x3]     [  0.00]

Matriz aumentada asociada al sistema:
 [[-0.6  0.2  0.2  0. ]
 [ 0.1 -0.3  0.2  0. ]
 [ 0.5  0.1 -0.4  0. ]] 

Tamaño de A:
 (3, 3)

Tamaño de B:
 (3, 1)

Matriz escalonada reducida:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]

Solución del sistema:
x1 = 0.0
x2 = 0.0
x3 = 0.0
