# Examen Parcial 2

**Nombre:** Heriberto Espino Montelongo

**Materia:** Análisis numérico

**Sección:** 1

**Fecha:** 14/10/2024

Conteste las siguientes preguntas:
1. ¿Es un sistema de ecuaciones lineales?.

    A. Sí

    B. No

1. En caso afirmativo, conteste lo siguiente:

    (a) ¿Cuál es la ecuación matricial Ax = b del sistema?

    (b) ¿Cuál es la matriz aumentada asociada al sistema?

    (c) ¿Es posible calcular el tamaño de A?

    (d) ¿Es posible calcular el tamaño de b?

    (e) ¿Es posible aplicar el método de Gauss-Jordan? En caso afirmativo, determine cuál es la forma escalonada reducida escalonada por renglones asociada a la matriz aumentada y con esta forma determine cuál es la solución del SEL. O en otro caso, justifique por qué no tiene solución.

    (f) Determine cuál es la solución del SEL. O en otro caso, justifique por qué no tiene solución.

### Funciones

In [154]:
import numpy as np

def selsol(A, B):

    print("Sí es un sistema de ecuaciones lineales\n")

    # a) La ecuacuión matricial Ax = b del sistema -----------------------------------------------------------------
    print("Ecuación matricial Ax = b del sistema")

    # Determine the width of the columns
    col_width = max(len("{:.2f}".format(num)) for row in A for num in row) + 2
    vec_width = max(len("{:.2f}".format(num)) for num in B.flatten()) + 2

    # mprimir la ecuación matricial
    for i in range(A.shape[0]):
        row = ["{:.2f}".format(num).rjust(col_width) for num in A[i]]
        if i == A.shape[0] // 2:
            print("[{}]  *  [x{}]  =  [{}]".format(" ".join(row), i + 1, "{:.2f}".format(B[i, 0]).rjust(vec_width)))
        else:
            print("[{}]     [x{}]     [{}]".format(" ".join(row), i + 1, "{:.2f}".format(B[i, 0]).rjust(vec_width)))

    # b) La matriz aumentada asociada al sistema ---------------------------------------------------------------------
    C = np.concatenate((A, B), axis=1)
    print("\nMatriz aumentada asociada al sistema:\n", C, "\n")

    # Convertir a float para evitar problemas con la división
    C = np.array(C, dtype=float)

    sizeA = np.shape(A)
    sizeB = np.shape(B)
    sizeC = np.shape(C)

    # C Y D, tamamño de A y B

    print("Tamaño de A:\n", sizeA)
    print("\nTamaño de B:\n", sizeB)

    # c) Determinante de A --------------------------------------------------------------------------------------------

    # If determinant is close to zero, multiply C by 10 and recalculate
    detA = np.linalg.det(A)

    if np.isclose(detA, 0, 0.0001) and detA!=0:
        while np.isclose(detA, 0, 0.0001) and detA!=0:
            print("Posible error numérico. Multiplicando la matriz aumentada por 10 y recalculando.")
            C *= 10
            A = C[:, :-1]
            B = C[:, -1].reshape(-1, 1)
            detA = np.linalg.det(A)
            print("Nuevo determinante de A: ", detA)
    else:
        print("\nDeterminante de A: ", detA)

    # d) Determinante de B
    try:
        detB = np.linalg.det(B)
        print("\nDeterminante de B: ", detB)
    except np.linalg.LinAlgError:
        print("\nNo es posible calcular el determinante de B porque no es una matriz cuadrada.") # :p

    # e) Aplicar el método de Gauss-Jordan -----------------------------------------------------------------------------
    for c in range(sizeC[1] - 1):
        if C[c][c] == 0:
            for r in range(c + 1, sizeC[0]):
                if C[r][c] != 0:
                    C[[c, r]] = C[[r, c]]
                    break

        if C[c][c] != 0:
            C[c, :] = C[c, :] / C[c][c]

        for r in range(sizeC[0]):
            if r != c:
                C[r, :] = C[r, :] - C[r][c] * C[c, :]

    # e) Matriz escalonada reducida -----------------------------------------------------------------------------------
    print("\nMatriz escalonada reducida por renglones de la matriz aumentada:\n", C)

# e) Determine cuál es la solución del SEL. O en otro caso, justifique por qué no tiene solución ------------------    

    if detA == 0:
        print("\nEl sistema no tiene solución o tiene infinitas soluciones, el determinante es 0.")
        pivotes = []  # Lista para almacenar las columnas de los pivotes

    # Para cada row de la matriz escalonada reducida
    for r in range(sizeC[0]):
        # Caso: el sistema no tiene solución (alguna fila tiene todos 0, excepto el último)
        if np.all(C[r, :-1] == 0) and C[r, -1] != 0:
            print("\nEl sistema no tiene solución.")
            return

        # Caso: el sistema tiene infinitas soluciones (alguna fila tiene todos 0, incluyendo el último)
        elif np.all(C[r, :-1] == 0) and C[r, -1] == 0:
            print("\nEl sistema tiene infinitas soluciones.")
            
            # Imprimir las ecuaciones de las filas no nulas
            for r in range(sizeC[0]):
                if not np.all(C[r, :-1] == 0):
                    ecuacion = " + ".join([f"{C[r, c]:.3f}*x{c+1}" for c in range(sizeC[1] - 1) if C[r, c] != 0])
                    print(f"{ecuacion} = {C[r, -1]:.3f}")
                    # Registrar el índice de las variables pivote
                    for c in range(sizeC[1] - 1):
                        if C[r, c] != 0:
                            pivotes.append(c)
                            break
            
            # Identificar e imprimir las variables libres
            va_lib = [f"x{c+1}" for c in range(sizeC[1] - 1) if c not in pivotes]
            if va_lib:
                for var in va_lib:
                    print(f"{var} ∈ ℝ")
            else:
                print("\nNo hay variables libres.")
            
            return
    solutions = np.linalg.solve(A, B)
    print("\nSoluciones del sistema:")
    for i, sol in enumerate(solutions):
        print(f"x{i+1} = {sol}")
    

### Ejercicio 1

$$
x_1 - 2x_2 + 3x_3 = 11 \\
4x_1 + x_2 - x_3 = 4 \\
2x_1 - x_2 + 3x_3 = 10
$$

In [155]:
A = np.array([[1, -2, 3], [4, 1, -1], [2, -1, 3]])
B = np.array([[11], [4], [10]])

selsol(A, B)

Sí es un sistema de ecuaciones lineales

Ecuación matricial Ax = b del sistema
[   1.00   -2.00    3.00]     [x1]     [  11.00]
[   4.00    1.00   -1.00]  *  [x2]  =  [   4.00]
[   2.00   -1.00    3.00]     [x3]     [  10.00]

Matriz aumentada asociada al sistema:
 [[ 1 -2  3 11]
 [ 4  1 -1  4]
 [ 2 -1  3 10]] 

Tamaño de A:
 (3, 3)

Tamaño de B:
 (3, 1)

Determinante de A:  11.999999999999995

No es posible calcular el determinante de B porque no es una matriz cuadrada.

Matriz escalonada reducida por renglones de la matriz aumentada:
 [[ 1.  0.  0.  2.]
 [ 0.  1.  0. -3.]
 [ 0.  0.  1.  1.]]

Soluciones del sistema:
x1 = [2.]
x2 = [-3.]
x3 = [1.]


### Ejercicio 2

$$
9x_2  -7x_3 = 2 \\
- x_3 = -2 \\
-3x_1 + 6x_2 + 8x_3 = 1
$$

In [156]:
A = np.array([[0, 9, -7], [0, 0, -1], [-3, 6, 8]])
B = np.array([[2], [-2], [1]])

selsol(A, B)

Sí es un sistema de ecuaciones lineales

Ecuación matricial Ax = b del sistema
[   0.00    9.00   -7.00]     [x1]     [   2.00]
[   0.00    0.00   -1.00]  *  [x2]  =  [  -2.00]
[  -3.00    6.00    8.00]     [x3]     [   1.00]

Matriz aumentada asociada al sistema:
 [[ 0  9 -7  2]
 [ 0  0 -1 -2]
 [-3  6  8  1]] 

Tamaño de A:
 (3, 3)

Tamaño de B:
 (3, 1)

Determinante de A:  27.0

No es posible calcular el determinante de B porque no es una matriz cuadrada.

Matriz escalonada reducida por renglones de la matriz aumentada:
 [[ 1.          0.          0.          8.55555556]
 [ 0.          1.          0.          1.77777778]
 [-0.         -0.          1.          2.        ]]

Soluciones del sistema:
x1 = [8.55555556]
x2 = [1.77777778]
x3 = [2.]


### Ejercicio 3
$$
x_1 + 2x_2 - 2x_3 - x_4 = 1 \\
-3x_1 + 4x_2 + x_3 - 2x_4 = 4 \\
-3x_1 + 14x_2 - 4x_3 - 7x_4 = 3 \\
6x_1 + 12x_2 - 12x_3 - 6x_4 = 5 \\
$$

In [157]:
A = np.array([[1, 2, -2, -1], [-3, 4, 1, -2], [-3, 14, -4, -7], [6, 12, -12, -6]])
B = np.array([[1], [4], [3], [5]])

selsol(A, B)

Sí es un sistema de ecuaciones lineales

Ecuación matricial Ax = b del sistema
[    1.00     2.00    -2.00    -1.00]     [x1]     [  1.00]
[   -3.00     4.00     1.00    -2.00]     [x2]     [  4.00]
[   -3.00    14.00    -4.00    -7.00]  *  [x3]  =  [  3.00]
[    6.00    12.00   -12.00    -6.00]     [x4]     [  5.00]

Matriz aumentada asociada al sistema:
 [[  1   2  -2  -1   1]
 [ -3   4   1  -2   4]
 [ -3  14  -4  -7   3]
 [  6  12 -12  -6   5]] 

Tamaño de A:
 (4, 4)

Tamaño de B:
 (4, 1)

Determinante de A:  0.0

No es posible calcular el determinante de B porque no es una matriz cuadrada.

Matriz escalonada reducida por renglones de la matriz aumentada:
 [[ 1.   0.  -1.   0.  -8.4]
 [ 0.   1.  -0.5 -0.5 -3.8]
 [ 0.   0.   0.   0.  -8. ]
 [ 0.   0.   0.   0.  -1. ]]

El sistema no tiene solución o tiene infinitas soluciones, el determinante es 0.

El sistema no tiene solución.


### Ejercicio 4

$$
-2x_1 + x_2 + 6x_3 = 18 \\
5x_1 + 8x_3 = -16 \\
3x_1 + 2x_2 - 10x_3 = -3
$$

In [158]:
A = np.array([[-2, 1, 6], [5, 0, 8], [3, 2, -10]])
B = np.array([[18], [-16], [-3]])

selsol(A, B)

Sí es un sistema de ecuaciones lineales

Ecuación matricial Ax = b del sistema
[   -2.00     1.00     6.00]     [x1]     [   18.00]
[    5.00     0.00     8.00]  *  [x2]  =  [  -16.00]
[    3.00     2.00   -10.00]     [x3]     [   -3.00]

Matriz aumentada asociada al sistema:
 [[ -2   1   6  18]
 [  5   0   8 -16]
 [  3   2 -10  -3]] 

Tamaño de A:
 (3, 3)

Tamaño de B:
 (3, 1)

Determinante de A:  166.00000000000006

No es posible calcular el determinante de B porque no es una matriz cuadrada.

Matriz escalonada reducida por renglones de la matriz aumentada:
 [[ 1.   0.   0.  -4. ]
 [ 0.   1.   0.   7. ]
 [-0.  -0.   1.   0.5]]

Soluciones del sistema:
x1 = [-4.]
x2 = [7.]
x3 = [0.5]


### Ejercicio 5

$$
3x_1 + 6x_2 - 6x_3 = 9 \\
2x_1 - 5x_2 + 4x_3 = 6 \\
5x_1 + 28x_2 - 26x_3 = -8
$$

In [159]:
A = np.array([[3, 6, -6], [2, -5, 4], [5, 28, -26]])
B = np.array([[9], [6], [-8]])

selsol(A, B)

Sí es un sistema de ecuaciones lineales

Ecuación matricial Ax = b del sistema
[    3.00     6.00    -6.00]     [x1]     [   9.00]
[    2.00    -5.00     4.00]  *  [x2]  =  [   6.00]
[    5.00    28.00   -26.00]     [x3]     [  -8.00]

Matriz aumentada asociada al sistema:
 [[  3   6  -6   9]
 [  2  -5   4   6]
 [  5  28 -26  -8]] 

Tamaño de A:
 (3, 3)

Tamaño de B:
 (3, 1)
Posible error numérico. Multiplicando la matriz aumentada por 10 y recalculando.
Nuevo determinante de A:  0.0

No es posible calcular el determinante de B porque no es una matriz cuadrada.

Matriz escalonada reducida por renglones de la matriz aumentada:
 [[ 1.00000000e+00  0.00000000e+00 -2.22222222e-01 -4.81111111e+01]
 [ 0.00000000e+00  1.00000000e+00 -8.88888889e-01 -2.04444444e+02]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 -2.30000000e+02]]

El sistema no tiene solución o tiene infinitas soluciones, el determinante es 0.

El sistema no tiene solución.


### Ejercicio 6

$$
x_1 - 2x_2 + x_3 + x_4 = 2 \\
3x_1 + 2x_3 - 2x_4 = -8 \\
4x_2 - x_3 - x_4 = 1 \\
5x_1 + 3x_3 - x_4 = 0 \\
$$

In [160]:
A = np.array([[1, -2, 1, 1], [3, 0, 2, -2], [0, 4, -1, -1], [5, 0, 3, -1]])
B = np.array([[2], [-8], [1], [0]])

selsol(A, B)

Sí es un sistema de ecuaciones lineales

Ecuación matricial Ax = b del sistema
[   1.00   -2.00    1.00    1.00]     [x1]     [   2.00]
[   3.00    0.00    2.00   -2.00]     [x2]     [  -8.00]
[   0.00    4.00   -1.00   -1.00]  *  [x3]  =  [   1.00]
[   5.00    0.00    3.00   -1.00]     [x4]     [   0.00]

Matriz aumentada asociada al sistema:
 [[ 1 -2  1  1  2]
 [ 3  0  2 -2 -8]
 [ 0  4 -1 -1  1]
 [ 5  0  3 -1  0]] 

Tamaño de A:
 (4, 4)

Tamaño de B:
 (4, 1)
Posible error numérico. Multiplicando la matriz aumentada por 10 y recalculando.
Nuevo determinante de A:  0.0

No es posible calcular el determinante de B porque no es una matriz cuadrada.

Matriz escalonada reducida por renglones de la matriz aumentada:
 [[ 1.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   3.37769972e+16]
 [ 0.00000000e+00  1.00000000e+00  0.00000000e+00  0.00000000e+00
  -1.68884986e+16]
 [-0.00000000e+00 -0.00000000e+00  1.00000000e+00  0.00000000e+00
  -5.91097451e+16]
 [-0.00000000e+00 -0.00

En este caso le hacemos caso a "El sistema no tiene solución o tiene infinitas soluciones, el determinante es 0".

### Ejercicio 7

$$
3x_1 + 6x_2 - 6x_3 = 9 \\
2x_1 - 5x_2 + 4x_3 = 6 \\
-x_1 + 16x_2 - 14x_3 = -3
$$

In [161]:
A = np.array([[3, 6, -6], [2, -5, 4], [-1, 16, -14]])
B = np.array([[9], [6], [-3]])

selsol(A, B)

Sí es un sistema de ecuaciones lineales

Ecuación matricial Ax = b del sistema
[    3.00     6.00    -6.00]     [x1]     [   9.00]
[    2.00    -5.00     4.00]  *  [x2]  =  [   6.00]
[   -1.00    16.00   -14.00]     [x3]     [  -3.00]

Matriz aumentada asociada al sistema:
 [[  3   6  -6   9]
 [  2  -5   4   6]
 [ -1  16 -14  -3]] 

Tamaño de A:
 (3, 3)

Tamaño de B:
 (3, 1)

Determinante de A:  0.0

No es posible calcular el determinante de B porque no es una matriz cuadrada.

Matriz escalonada reducida por renglones de la matriz aumentada:
 [[ 1.          0.         -0.22222222  3.        ]
 [ 0.          1.         -0.88888889  0.        ]
 [ 0.          0.          0.          0.        ]]

El sistema no tiene solución o tiene infinitas soluciones, el determinante es 0.

El sistema tiene infinitas soluciones.
1.000*x1 + -0.222*x3 = 3.000
1.000*x2 + -0.889*x3 = 0.000
x3 ∈ ℝ


### Ejercicio 8

$$
x_1 + x_2 - x_3 = 7 \\
4x_1 - x_2 + 5x_3 = 4 \\
2x_1 + 2x_2 - 3x_3 = 0
$$

In [163]:
A = np.array([[1, 1, -1], [4, -1, 5], [2, 2, -3]])
B = np.array([[7], [4], [0]])

selsol(A, B)

Sí es un sistema de ecuaciones lineales

Ecuación matricial Ax = b del sistema
[   1.00    1.00   -1.00]     [x1]     [  7.00]
[   4.00   -1.00    5.00]  *  [x2]  =  [  4.00]
[   2.00    2.00   -3.00]     [x3]     [  0.00]

Matriz aumentada asociada al sistema:
 [[ 1  1 -1  7]
 [ 4 -1  5  4]
 [ 2  2 -3  0]] 

Tamaño de A:
 (3, 3)

Tamaño de B:
 (3, 1)

Determinante de A:  5.000000000000001

No es posible calcular el determinante de B porque no es una matriz cuadrada.

Matriz escalonada reducida por renglones de la matriz aumentada:
 [[ 1.  0.  0. -9.]
 [-0.  1.  0. 30.]
 [-0. -0.  1. 14.]]

Soluciones del sistema:
x1 = [-9.]
x2 = [30.]
x3 = [14.]


### Ejercicio 9

$$
x_1 + 2x_2 + 2x_3 - x_4 = 1 \\
-3x_1 + 4x_2 + x_3 - 2x_4 = 4 \\
-3x_1 + 14x_2 + 4x_3 - 7x_4 = 3 \\
6x_1 + 12x_2 - 12x_3 - 6x_4 = 5 \\
$$

In [164]:
A = np.array([[1, 2, 2, -1], [-3, 4, 1, -2], [-3, 14, 4, -7], [6, 12, -12, -6]])
B = np.array([[1], [4], [3], [5]])

selsol(A, B)

Sí es un sistema de ecuaciones lineales

Ecuación matricial Ax = b del sistema
[    1.00     2.00     2.00    -1.00]     [x1]     [  1.00]
[   -3.00     4.00     1.00    -2.00]     [x2]     [  4.00]
[   -3.00    14.00     4.00    -7.00]  *  [x3]  =  [  3.00]
[    6.00    12.00   -12.00    -6.00]     [x4]     [  5.00]

Matriz aumentada asociada al sistema:
 [[  1   2   2  -1   1]
 [ -3   4   1  -2   4]
 [ -3  14   4  -7   3]
 [  6  12 -12  -6   5]] 

Tamaño de A:
 (4, 4)

Tamaño de B:
 (4, 1)

Determinante de A:  0.0

No es posible calcular el determinante de B porque no es una matriz cuadrada.

Matriz escalonada reducida por renglones de la matriz aumentada:
 [[ 1.   0.   0.   0.  -1.6]
 [ 0.   1.   0.  -0.5 22.8]
 [ 0.   0.   1.   0.   2. ]
 [ 0.   0.   0.   0.  47. ]]

El sistema no tiene solución o tiene infinitas soluciones, el determinante es 0.

El sistema no tiene solución.


### Ejercicio 10

$$
3x^{1/2} - 2y = 4 \\
5x + 2y = 12
$$

No es un sistema de ecuaciones lineales porque hay un $x^{1/2}$