# Sistemas de Ecuaciones Lineales

**Nombre:** Heriberto Espino Montelongo

**Materia:** Análisis numérico

**Sección:** 1

**Fecha:** 11/09/2024

In [2]:
import numpy as np 

# Solution 1

In [3]:
# matriz de coeficientes
A = np.array([[1, .5, -.5], [1, 1, 1], [1, -2, -3]])  # 3x3

# vetor de terminos independentes
b = np.array([[1.5], [1], [4]])  # 3x1

In [10]:
print("Solution:")

print(np.linalg.solve(A, b))

Solution:
[[ 2.]
 [-1.]
 [ 0.]]


## Solution 2

In [11]:
A = np.array([[3,-2], [5,2]]) 
b = np.array([[4], [12]])

In [13]:
print("Solution 2:")

print(np.linalg.solve(A, b))

Solution 2:
[[2.]
 [1.]]


## Solution 3

In [14]:
A = np.array([[1,-1], [2,-2]]) 
b = np.array([[7], [14]])  

In [ ]:
print("Solution 3:")

print(np.linalg.solve(A, b))

In [20]:
print("Solution 3:")

if np.linalg.det(A) != 0:
    print(np.linalg.solve(A, b))
else:
    print("The system has no solution or has infinite solutions")


Solution 2:
The system has no solution or has infinite solutions


## Solution 4

In [21]:
A = np.array([[1,-1], [2,-2]]) 
b = np.array([[7], [10]])

In [23]:
print("Solution 4:")

if np.linalg.det(A) != 0:
    print(np.linalg.solve(A, b))
else:
    print("The system has no solution or has infinite solutions")

Solution 4:
The system has no solution or has infinite solutions


## Solution 5:

In [24]:
A = np.array([[2,-3,1], [1,-1,2], [3,1,-1]])
b = np.array([[-1], [-3], [9]])

In [26]:
print("Solution 5:")

if np.linalg.det(A) != 0:
    print(np.linalg.solve(A, b))
else:
    print("The system has no solution or has infinite solutions")

Solution 5:
[[ 2.]
 [ 1.]
 [-2.]]


## Solution 6

In [27]:
A = np.array([[1,-1,4], [3,0,1], [-1,1,-4]])
b = np.array([[5], [0], [20]])

In [28]:
print("Solution 6:")

if np.linalg.det(A) != 0:
    print(np.linalg.solve(A, b))
else:
    print("The system has no solution or has infinite solutions")

Solution :
The system has no solution or has infinite solutions


## Solution 7

In [31]:
A = np.array([[-1,1,2], [1,2,1], [-2,-1,1]])
b = np.array([[0], [6], [-6]])

In [32]:
print("Solution 7:")

if np.linalg.det(A) != 0:
    print(np.linalg.solve(A, b))
else:
    print("The system has no solution or has infinite solutions")

Solution 7:
The system has no solution or has infinite solutions


## Solution 8

In [35]:
A = np.array([[-.8,.7], [.8,-.7]])
b = np.array([[0], [0]])

In [36]:
print("Solution 8:")

if np.linalg.det(A) != 0:
    print(np.linalg.solve(A, b))
else:
    print("The system has no solution or has infinite solutions")

Solution 8:
The system has no solution or has infinite solutions


## Solution 9

In [37]:
A = np.array([[-.8,.8,.4], [.3,-.9,.4], [.5,.1,-.8]])
b = np.array([[0], [0], [0]]) 

In [38]:
print("Solution 9:")

if np.linalg.det(A) != 0:
    print(np.linalg.solve(A, b))
else:
    print("The system has no solution or has infinite solutions")

Solution 9:
The system has no solution or has infinite solutions


## Solution 10

In [39]:
A = np.array([[-.35,.3,.3,.2], [.1,-.9,.15,.1], [.25,.35,-.85,.3],[0,.25,.4,-.6]])
b = np.array([[0], [0], [0], [0]]) 

In [40]:
print("Solution 10:")

if np.linalg.det(A) != 0:
    print(np.linalg.solve(A, b))
else:
    print("The system has no solution or has infinite solutions")

Solution 10:
[[-0.]
 [-0.]
 [ 0.]
 [ 0.]]


Está ingresando al primer if, no al else.

Python encontró el determinante así:

In [41]:
print(np.linalg.det(A))

-2.989275493803247e-17


-0.00000000000000002

Pero sí es cero.