# Arreglos

**Nombre:** Heriberto Espino Montelongo

**Materia:** Análisis Numérico

**Sección:** 1

**Fecha:** 02/09/2024

In [5]:
# declaración
b = [1, 2, 3, 4, 5]

# acceso
elemento1 = b[0]
elemento2 = b[1]

# impresión
print("el valor de b[0] es", elemento1)
print("el valor de b[1] es",elemento2)

el valor de b[0] es 1
el valor de b[1] es 2


In [6]:
a = ['r', 'o', 'o', 't']
print(a)

['r', 'o', 'o', 't']


In [8]:
c = ['a', 'n', 's']

print(a+b+c)

['r', 'o', 'o', 't', 1, 2, 3, 4, 5, 'a', 'n', 's']


In [10]:
b = [1, 2, 3, 4, 5]
b_aprox = [1.1, 2.1, 3.1, 4.4, 5.5]

print(b + b_aprox)

[1, 2, 3, 4, 5, 1.1, 2.1, 3.1, 4.4, 5.5]


El símbolo de sumar es concatentar

# Arreglos numéricos en Python

In [24]:
from numpy import linspace
# es igual a importar "import numpy as np" y luego llamar a la función como "np.linspace"

x = linspace(0, 2, 3)
# linspace(inicio, fin, cantidad de elementos)

print(x)
# son 3 elementos entre 0 y 2, las particiones

print(type(x))

print(type(x[0]))

[0. 1. 2.]
<class 'numpy.ndarray'>
<class 'numpy.float64'>


In [14]:
import numpy as np

x = np.linspace(0, 2, 3)
y = np.linspace(0, 10, 6)

print(x)
print(y)

print(x + y) # Da error porque tienen que ser del mismo tamaño

[0. 1. 2.]
[ 0.  2.  4.  6.  8. 10.]


ValueError: operands could not be broadcast together with shapes (3,) (6,) 

## Funcion zeros

In [23]:
from numpy import zeros

x = zeros(3, int) # array de 3 elementos con valor 0
y = zeros(3) # array de 3 elementos con valor 0.0

print("Vectores x e y:")
print(x)
print(y)

print("\nNúmero de elementos de x e y:")
print(len(x))
print(len(y))

Vectores x e y:
[0 0 0]
[0. 0. 0.]

Número de elementos de x e y:
3
3


## Función 'array'

In [20]:
from numpy import array

x = array([1, 2, 3, 4, 5])
print("Son elementos enteros")
print(x)

x = array([1., 2., 3., 4., 5.])
print("\nSon elementos flotantes")
print(x)

Son elementos enteros
[1 2 3 4 5]

Son elementos flotantes
[1. 2. 3. 4. 5.]


# Array

In [28]:
c = ['a', 'n', 's']
a = ['r', 'o', 'o', 't']
print(a)

b = np.array([1, 2, 3, 4, 5])
b_aprox = np.array([1.1, 2.2, 3.3, 4.4, 5.5])
print(b + b_aprox)

['r', 'o', 'o', 't']
[ 2.1  4.2  6.3  8.4 10.5]


In [29]:
print("Error absoluto")
print(abs(b - b_aprox))

Error absoluto
[0.1 0.2 0.3 0.4 0.5]


In [31]:
print("Lista de listas o listas anidadas")
m = [a, b, c]
print(m)

Lista de listas o listas anidadas
[['r', 'o', 'o', 't'], array([1, 2, 3, 4, 5]), ['a', 'n', 's']]


In [34]:
print("Matriz con Python")
matriz = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
print(matriz)

Matriz con Python
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [35]:
print("Matriz con NumPy")
matriz = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(matriz)

Matriz con NumPy
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [38]:
print("Acceso a matrices")

matriz = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

elemento00 = matriz[0, 0]
elemento01 = matriz[0, 1]
elemento02 = matriz[2, 2]

print("Elemento en la posición 0, 0:", elemento00)
print("Elemento en la posición 0, 1:", elemento01)
print("Elemento en la posición 2, 2:", elemento02)


Acceso a matrices
Elemento en la posición 0, 0: 1
Elemento en la posición 0, 1: 2
Elemento en la posición 2, 2: 9
