# Ejercicios SEL

**Nombre:** Heriberto Espino Montelongo

**Materia:** Análisis numérico

**Sección:** 1

**Fecha:** 30/09/2024

In [1]:
from pprint import pprint
import sympy as sp
from sympy import Matrix
import numpy as np

def no_meter_decimales(augmented_A): 
    print('The augmented matrix (A|b):')
    pprint(augmented_A)
    
    # Convert the augmented matrix to a sympy Matrix
    augmented_A = Matrix(augmented_A)
    
    # Extract A and b from the augmented matrix
    A = augmented_A[:, :-1]
    b = augmented_A[:, -1]
    
    # Convert A and b to numpy arrays
    A = np.array(A).astype(np.float64)
    b = np.array(b).astype(np.float64)
    
    # Compute the row echelon form using sympy
    A_new = augmented_A.rref()[0]
    print('\nThe row echelon form of the matrix is:')
    pprint(A_new)

    # Compute the determinant of A
    detA = np.linalg.det(A)

    if detA == 0:
        print("\nThe system of linear equations has no solution or infinitely many solutions.")
    else: 
        print("\nThe system of linear equations has exactly one solution:")

## Ejercicios SEL 2x2

### 1. Una única solución

In [4]:
augmented_A = sp.Matrix([[3, -2, 4],[5, 2, 12]])
no_meter_decimales(augmented_A)


The augmented matrix (A|b):
Matrix([
[3, -2,  4],
[5,  2, 12]])

The row echelon form of the matrix is:
Matrix([
[1, 0, 2],
[0, 1, 1]])

The system of linear equations has exactly one solution:


### 2. Infinitas soluciones

In [5]:
augmented_A = sp.Matrix([[1, -1, 7],[2, -2, 14]])
no_meter_decimales(augmented_A)

The augmented matrix (A|b):
Matrix([
[1, -1,  7],
[2, -2, 14]])

The row echelon form of the matrix is:
Matrix([
[1, -1, 7],
[0,  0, 0]])

The system of linear equations has no solution or infinitely many solutions.


### 3. No tiene solución

In [6]:
augmented_A = sp.Matrix([[1, -1, 7],[2, -2, 10]])
no_meter_decimales(augmented_A)


The augmented matrix (A|b):
Matrix([
[1, -1,  7],
[2, -2, 10]])

The row echelon form of the matrix is:
Matrix([
[1, -1, 0],
[0,  0, 1]])

The system of linear equations has no solution or infinitely many solutions.


### X. Extra

In [7]:
augmented_A = sp.Matrix([[-.8, .7, 0],[.8, -.7, 0]])
no_meter_decimales(augmented_A)

The augmented matrix (A|b):
Matrix([
[-0.8,  0.7, 0],
[ 0.8, -0.7, 0]])

The row echelon form of the matrix is:
Matrix([
[1, -0.875, 0],
[0,      0, 0]])

The system of linear equations has no solution or infinitely many solutions.


### Otros ejercicios

In [8]:
C = np.arange(16)
print(C)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [9]:
C.shape = (4,4)  # reordena el arreglo anterior a un arreglo de 4x4
print(C)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [10]:
print('Primera fila', C[0])

Primera fila [0 1 2 3]


In [11]:
print('Última fila', C[-1])

Última fila [12 13 14 15]


In [12]:
E = np.zeros((8,8))
E

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [13]:
for i in range(8):
    E[i][i] = 1
E

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [14]:
F = np.ones((4,5))
print(F)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [15]:
F.astype(int)  
F

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [16]:
augmented_F = Matrix(F)
pprint(augmented_F)

Matrix([
[1.0, 1.0, 1.0, 1.0, 1.0],
[1.0, 1.0, 1.0, 1.0, 1.0],
[1.0, 1.0, 1.0, 1.0, 1.0],
[1.0, 1.0, 1.0, 1.0, 1.0]])


In [17]:
augmented_F.rref()[0]

Matrix([
[1, 1.0, 1.0, 1.0, 1.0],
[0,   0,   0,   0,   0],
[0,   0,   0,   0,   0],
[0,   0,   0,   0,   0]])

## Ejercicios SEL 3x3

### 4. Una única solución

In [18]:
augmented_A = sp.Matrix([[2, -3, 1, -1],[1, -1, 2, -3], [3, 1, -1, 9]])
no_meter_decimales(augmented_A)

The augmented matrix (A|b):
Matrix([
[2, -3,  1, -1],
[1, -1,  2, -3],
[3,  1, -1,  9]])

The row echelon form of the matrix is:
Matrix([
[1, 0, 0,  2],
[0, 1, 0,  1],
[0, 0, 1, -2]])

The system of linear equations has exactly one solution:


### 5. No tiene soluciones

In [19]:
augmented_A = sp.Matrix([[1, -1, 4, -5],[3, 0, 1, 0], [-1, 1, -4, 20]])
no_meter_decimales(augmented_A)

The augmented matrix (A|b):
Matrix([
[ 1, -1,  4, -5],
[ 3,  0,  1,  0],
[-1,  1, -4, 20]])

The row echelon form of the matrix is:
Matrix([
[1, 0,   1/3, 0],
[0, 1, -11/3, 0],
[0, 0,     0, 1]])

The system of linear equations has no solution or infinitely many solutions.


$$ 0 =1 \!$$

### 6. Infinitas soluciones

In [20]:
augmented_A = sp.Matrix([[-1, 1, 2, 0],[1, 2, 1, 6], [-2, -1, 1, -6]])
no_meter_decimales(augmented_A)


The augmented matrix (A|b):
Matrix([
[-1,  1, 2,  0],
[ 1,  2, 1,  6],
[-2, -1, 1, -6]])

The row echelon form of the matrix is:
Matrix([
[1, 0, -1, 2],
[0, 1,  1, 2],
[0, 0,  0, 0]])

The system of linear equations has no solution or infinitely many solutions.


$$ x = z - 2 $$
$$y = z-2$$
$$ z \in \R$$

### 7. Decimales

In [21]:
augmented_A = sp.Matrix([[-.6, .2, .2, 0],[.1, -.3, .2, 0], [.5, .1, -.4, 0]])
no_meter_decimales(augmented_A)

The augmented matrix (A|b):
Matrix([
[-0.6,  0.2,  0.2, 0],
[ 0.1, -0.3,  0.2, 0],
[ 0.5,  0.1, -0.4, 0]])

The row echelon form of the matrix is:
Matrix([
[1, 0, 0, 0],
[0, 1, 0, 0],
[0, 0, 1, 0]])

The system of linear equations has exactly one solution:


$$ x = 0 $$
$$y = 0$$
$$ z = 0$$

In [22]:
augmented_A = sp.Matrix([[-6, 2, 2, 0],[1, -3, 2, 0], [5, 1, -4, 0]])
no_meter_decimales(augmented_A)

The augmented matrix (A|b):
Matrix([
[-6,  2,  2, 0],
[ 1, -3,  2, 0],
[ 5,  1, -4, 0]])

The row echelon form of the matrix is:
Matrix([
[1, 0, -5/8, 0],
[0, 1, -7/8, 0],
[0, 0,    0, 0]])

The system of linear equations has no solution or infinitely many solutions.
