# Errores numericos

**Nombre:** Heriberto Espino Montelongo

**Materia:** Análisis numérico

**Sección:** 1

**Fecha:** 03/10/2024

En este documento, abordaremos la verificación y resolución de sistemas de ecuaciones lineales utilizando el método de Gauss-Jordan.

#### Verificación de Sistemas de Ecuaciones Lineales

1. Verificar que es un Sistema de ecuaciones lineales.
     - Si tiene una potencia $x^2$ no es
     - Si tiene un producto $2xy$ no es 

2. ¿Tiene soluciones?
     - Si tiene un renglón de ceros, se pone $x_1 - x_2 = 7$
     - Si tiene un renglon con $0 = -4$ no tiene soluciones
     - Si tiene la diagonal de unos, tiene una única solución.

### Funciones

In [17]:
import numpy as np

def gaussian_elimination(A, B):

    print("Ecuación matricial Ax = b del sistema")
    # Determine the width of the columns
    col_width = max(len("{:.2f}".format(num)) for row in A for num in row) + 2
    vec_width = max(len("{:.2f}".format(num)) for num in B.flatten()) + 2

    # Print matrix A and vector B in columns
    for i in range(A.shape[0]):
        row = ["{:.2f}".format(num).rjust(col_width) for num in A[i]]
        if i == A.shape[0] // 2:
            print("[{}]  *  [x{}]  =  [{}]".format(" ".join(row), i + 1, "{:.2f}".format(B[i, 0]).rjust(vec_width)))
        else:
            print("[{}]     [x{}]     [{}]".format(" ".join(row), i + 1, "{:.2f}".format(B[i, 0]).rjust(vec_width)))

    # Concatenate A and B to form the augmented matrix
    C = np.concatenate((A, B), axis=1)
    print("\nMatriz aumentada asociada al sistema:\n", C, "\n")

    # Convert C to float
    C = np.array(C, dtype=float)

    sizeA = np.shape(A)
    sizeB = np.shape(B)
    sizeC = np.shape(C)

    print("Tamaño de A:\n", sizeA)
    print("\nTamaño de B:\n", sizeB)

    # print the determinant of A
    detA = np.linalg.det(A)
    print("\nDeterminante de A: ", detA)

    for c in range(sizeC[1] - 1):  # -1 to avoid the last column, because C is an augmented matrix
        # Pivot element check and row swap if necessary
        if C[c][c] == 0:
            for r in range(c + 1, sizeC[0]):
                if C[r][c] != 0:
                    C[[c, r]] = C[[r, c]]
                    break

        # Normalize the pivot row
        if C[c][c] != 0:
            C[c, :] = C[c, :] / C[c][c]

        # Zero out the current column for all other rows
        for r in range(sizeC[0]):
            if r != c:
                C[r, :] = C[r, :] - C[r][c] * C[c, :]

    print("\nMatriz escalonada reducida:\n", C)

    print("sol", print(np.linalg.solve(A, B)))

In [1]:
from pprint import pprint
import sympy as sp
from sympy import Matrix
import numpy as np

def no_meter_decimales(augmented_A): 
    print('The augmented matrix (A|b):')
    pprint(augmented_A)
    
    # Convert the augmented matrix to a sympy Matrix
    augmented_A = Matrix(augmented_A)
    
    # Extract A and b from the augmented matrix
    A = augmented_A[:, :-1]
    b = augmented_A[:, -1]
    
    # Convert A and b to numpy arrays
    A = np.array(A).astype(np.float64)
    b = np.array(b).astype(np.float64)
    
    # Compute the row echelon form using sympy
    A_new = augmented_A.rref()[0]
    print('\nThe row echelon form of the matrix is:')
    pprint(A_new)

    # Compute the determinant of A
    detA = np.linalg.det(A)

    if detA == 0:
        print("\nThe system of linear equations has no solution or infinitely many solutions.")
    else: 
        print("\nThe system of linear equations has exactly one solution:")

### Ejercicio 1

$$
3x_1 - 2x_2 = 4 \\
5x_1 + 2x_2 = 12
$$

In [18]:
A = np.array([[1, -2, 3], [4, 1, -1], [2, -1, 3]])
B = np.array([[11], [4], [10]])
C = sp.Matrix(np.column_stack((A, B)))

gaussian_elimination(A, B)
no_meter_decimales(C)
print(np.linalg.solve(A, B))

Ecuación matricial Ax = b del sistema
[   1.00   -2.00    3.00]     [x1]     [  11.00]
[   4.00    1.00   -1.00]  *  [x2]  =  [   4.00]
[   2.00   -1.00    3.00]     [x3]     [  10.00]

Matriz aumentada asociada al sistema:
 [[ 1 -2  3 11]
 [ 4  1 -1  4]
 [ 2 -1  3 10]] 

Tamaño de A:
 (3, 3)

Tamaño de B:
 (3, 1)

Determinante de A:  11.999999999999995

Matriz escalonada reducida:
 [[ 1.  0.  0.  2.]
 [ 0.  1.  0. -3.]
 [ 0.  0.  1.  1.]]
[[ 2.]
 [-3.]
 [ 1.]]
sol None
The augmented matrix (A|b):
Matrix([
[1, -2,  3, 11],
[4,  1, -1,  4],
[2, -1,  3, 10]])

The row echelon form of the matrix is:
Matrix([
[1, 0, 0,  2],
[0, 1, 0, -3],
[0, 0, 1,  1]])

The system of linear equations has exactly one solution:
[[ 2.]
 [-3.]
 [ 1.]]


### Ejercicio 2

$$
x_1 - x_2 = 7 \\
2x_1 - 2x_2 = 14
$$

In [19]:
A = np.array([[0, 9, -7], [0, 0, -1], [-3, 6, 8]])
C = sp.Matrix(np.column_stack((A, B)))

gaussian_elimination(A, B)
no_meter_decimales(C)
print(np.linalg.solve(A, B))

Ecuación matricial Ax = b del sistema
[   0.00    9.00   -7.00]     [x1]     [  11.00]
[   0.00    0.00   -1.00]  *  [x2]  =  [   4.00]
[  -3.00    6.00    8.00]     [x3]     [  10.00]

Matriz aumentada asociada al sistema:
 [[ 0  9 -7 11]
 [ 0  0 -1  4]
 [-3  6  8 10]] 

Tamaño de A:
 (3, 3)

Tamaño de B:
 (3, 1)

Determinante de A:  27.0

Matriz escalonada reducida:
 [[  1.           0.           0.         -17.77777778]
 [  0.           1.           0.          -1.88888889]
 [ -0.          -0.           1.          -4.        ]]
[[-17.77777778]
 [ -1.88888889]
 [ -4.        ]]
sol None
The augmented matrix (A|b):
Matrix([
[ 0, 9, -7, 11],
[ 0, 0, -1,  4],
[-3, 6,  8, 10]])

The row echelon form of the matrix is:
Matrix([
[1, 0, 0, -160/9],
[0, 1, 0,  -17/9],
[0, 0, 1,     -4]])

The system of linear equations has exactly one solution:
[[-17.77777778]
 [ -1.88888889]
 [ -4.        ]]


### Ejercicio 3

$$
x_1 - x_2 = 7 \\
2x_1 - 2x_2 = 10
$$

In [20]:
A = np.array([[1,2,-2,-1], [-3,4,1,-2], [-3,14,-4,-7], [6,12,-12,-6]])
B = np.array([[1], [4], [3], [5]])
C = sp.Matrix(np.column_stack((A, B)))

gaussian_elimination(A, B)
no_meter_decimales(C)

Ecuación matricial Ax = b del sistema
[    1.00     2.00    -2.00    -1.00]     [x1]     [  1.00]
[   -3.00     4.00     1.00    -2.00]     [x2]     [  4.00]
[   -3.00    14.00    -4.00    -7.00]  *  [x3]  =  [  3.00]
[    6.00    12.00   -12.00    -6.00]     [x4]     [  5.00]

Matriz aumentada asociada al sistema:
 [[  1   2  -2  -1   1]
 [ -3   4   1  -2   4]
 [ -3  14  -4  -7   3]
 [  6  12 -12  -6   5]] 

Tamaño de A:
 (4, 4)

Tamaño de B:
 (4, 1)

Determinante de A:  0.0

Matriz escalonada reducida:
 [[ 1.   0.  -1.   0.  -8.4]
 [ 0.   1.  -0.5 -0.5 -3.8]
 [ 0.   0.   0.   0.  -8. ]
 [ 0.   0.   0.   0.  -1. ]]


LinAlgError: Singular matrix

### Ejercicio 4

In [21]:
A = np.array([[-.6, .2, .2], [.1, -.3, .2], [.5, .1, -.4]])
B = np.array([[0], [0], [0]])

gaussian_elimination(A, B)

Ecuación matricial Ax = b del sistema
[  -0.60    0.20    0.20]     [x1]     [  0.00]
[   0.10   -0.30    0.20]  *  [x2]  =  [  0.00]
[   0.50    0.10   -0.40]     [x3]     [  0.00]

Matriz aumentada asociada al sistema:
 [[-0.6  0.2  0.2  0. ]
 [ 0.1 -0.3  0.2  0. ]
 [ 0.5  0.1 -0.4  0. ]] 

Tamaño de A:
 (3, 3)

Tamaño de B:
 (3, 1)

Determinante de A:  8.881784197001225e-18

Matriz escalonada reducida:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]
[[-0.]
 [ 0.]
 [ 0.]]
sol None


Por ejemplo, el error absoluto de el determinante es el musmo valor del determinante. Si lo hicieras a mano tendrias 0.